-- Dhamma Journey V7.2 Safe Feature Patch
-- NOTE: This migration has already been applied to Supabase project chworywxohcxvuhgwhpj.
-- Keep this file only as documentation / backup.

alter table public.buddhist_materials
  add column if not exists cover_url text;

alter table public.buddhist_market_items
  add column if not exists image_url text,
  add column if not exists gender text not null default 'all',
  add column if not exists sort_order integer not null default 0;

alter table public.buddhist_market_items
  drop constraint if exists buddhist_market_items_gender_check;
alter table public.buddhist_market_items
  add constraint buddhist_market_items_gender_check
  check (gender in ('all','male','female'));

create table if not exists public.buddhist_ai_knowledge (
  id bigint generated by default as identity primary key,
  category text not null default 'Umum',
  question text not null default '',
  keywords text[] not null default '{}',
  answer text not null,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.buddhist_content_marks (
  user_id uuid not null references auth.users(id) on delete cascade,
  content_type text not null check (content_type in ('video','material','audio')),
  content_key text not null,
  liked boolean not null default false,
  playlist boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key(user_id,content_type,content_key)
);
