(()=>{
"use strict";
const $=id=>document.getElementById(id), $$=sel=>Array.from(document.querySelectorAll(sel));
const base=(window.BUDDHIST_FALLBACK||[]).map((v,i)=>({...v,n:i+1,_local:true}));
let videos=base, materials=[], faqs=[], sops=[], active=0, sb=null, session=null, role="viewer", isAdmin=false, isOwner=false;
let editingVideo=null, editingMaterial=null, editingFaq=null, editingSop=null, authMode="login";
const KEY="buddhist-dashboard-state-v2";let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||"{}")}catch{}
let favorites=new Set(saved.favorites||[]),playlist=new Set(saved.playlist||[]),history=saved.history||[];
function persist(){localStorage.setItem(KEY,JSON.stringify({favorites:[...favorites],playlist:[...playlist],history}))}
function say(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove("show"),1800)}
function esc(s){return String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}
function keyOf(v){return String(v.id??v.n)}
function showPage(id){
  $$(".page-view").forEach(p=>p.classList.toggle("active",p.id===id));
  $$(".nav button[data-page]").forEach(b=>b.classList.toggle("active",b.dataset.page===id));
  document.querySelector(".info").style.display=id==="dashboard"?"block":"none";
  if(id==="tutorial")renderTutorial(); if(id==="faq")renderFAQ(); if(id==="sop")renderSOP(); if(id==="kategori")renderCategories();
  if(id==="favorit")renderListPage("favoriteGrid",[...favorites]); if(id==="playlist")renderListPage("playlistGrid",[...playlist]); if(id==="riwayat")renderListPage("historyGrid",history);
  if(id==="pengguna")renderUsers(); if(id==="activity-log")renderLogs();
  $("sidebar").classList.remove("open");$("mobileMenuBackdrop").classList.remove("show");
}
$$(".nav button[data-page]").forEach(b=>b.onclick=()=>showPage(b.dataset.page));
$("mobileMenuBtn").onclick=()=>{$("sidebar").classList.toggle("open");$("mobileMenuBackdrop").classList.toggle("show")};
$("mobileMenuBackdrop").onclick=()=>{$("sidebar").classList.remove("open");$("mobileMenuBackdrop").classList.remove("show")};
$("seeAllVideos").onclick=()=>showPage("tutorial");
function thumb(v){return v.thumbnail_url||v.thumb||"assets/thumb-1.png"}
function audioUrl(v){return v.video_url||v.audio||""}
function cardHTML(v,i){
 const k=keyOf(v),fav=favorites.has(k),lst=playlist.has(k);
 return `<article class="card" data-i="${i}">
 <div class="thumb"><img src="${esc(thumb(v))}" alt=""><span class="duration">${esc(v.duration||"")}</span></div>
 <h4>${esc(v.title)}</h4><p>${esc(v.pinyin||v.category||"")}</p>
 <div class="card-actions"><button class="mini-btn fav" data-k="${k}">${fav?"♥":"♡"} Favorit</button><button class="mini-btn list" data-k="${k}">${lst?"✓":"＋"} Playlist</button></div>
 <div class="card-admin-actions"><button class="mini-btn edit">✏ Edit</button><button class="mini-btn del">🗑 Hapus</button></div></article>`
}
function bindCards(scope){
 scope.querySelectorAll(".card").forEach(c=>{
   const i=+c.dataset.i;
   c.onclick=e=>{if(e.target.closest("button"))return;setActive(i,true);showPage("dashboard")};
   c.querySelector(".fav").onclick=e=>{e.stopPropagation();toggleFav(c.querySelector(".fav").dataset.k)};
   c.querySelector(".list").onclick=e=>{e.stopPropagation();toggleList(c.querySelector(".list").dataset.k)};
   c.querySelector(".edit")?.addEventListener("click",e=>{e.stopPropagation();openVideoForm(i)});
   c.querySelector(".del")?.addEventListener("click",e=>{e.stopPropagation();deleteVideo(i)});
 });
}
function renderCarousel(){
 const sc=$("scroller");sc.innerHTML=videos.map(cardHTML).join("");bindCards(sc);
 requestAnimationFrame(()=>updateCoverFlow());
}
function updateCoverFlow(){
 const sc=$("scroller");if(!sc)return;const r=sc.getBoundingClientRect(),center=r.left+r.width/2;let best=Infinity,ci=active;
 [...sc.children].forEach(c=>{const x=c.getBoundingClientRect(),d=Math.abs(x.left+x.width/2-center)/180;if(d<best){best=d;ci=+c.dataset.i}
 c.style.transform=`translateY(${-Math.max(0,20-d*8)}px) scale(${Math.max(.86,1.1-d*.1)})`;c.style.opacity=Math.max(.55,1-d*.12)});
 if(ci!==active && document.querySelector("#dashboard.active"))setActive(ci,false);
}
let dragging=false,sx=0,sl=0,moved=false;
$("scroller").addEventListener("scroll",updateCoverFlow,{passive:true});
$("scroller").addEventListener("wheel",e=>{if(Math.abs(e.deltaY)>Math.abs(e.deltaX)){$("scroller").scrollLeft+=e.deltaY*1.6;e.preventDefault()}},{passive:false});
$("scroller").addEventListener("pointerdown",e=>{if(e.target.closest("button"))return;dragging=true;moved=false;sx=e.clientX;sl=$("scroller").scrollLeft;$("scroller").setPointerCapture?.(e.pointerId)});
$("scroller").addEventListener("pointermove",e=>{if(!dragging)return;let dx=e.clientX-sx;if(Math.abs(dx)>3)moved=true;$("scroller").scrollLeft=sl-dx*1.5});
$("scroller").addEventListener("pointerup",()=>dragging=false);
function setActive(i,record=true){
 if(!videos.length)return;active=Math.max(0,Math.min(i,videos.length-1));const v=videos[active];
 $("heroTitle").textContent=v.title;$("infoTitle").textContent=v.title;$("infoPinyin").textContent=v.pinyin||"";$("infoDesc").textContent=v.description||"";
 $("duration").textContent=v.duration_label||v.duration||"-";$("category").textContent=v.category||"Mantra";$("infoThumb").src=thumb(v);
 $("infoFavBtn").textContent=favorites.has(keyOf(v))?"♥":"♡";renderMaterialsMini();
 const a=$("nativeAudio"),src=audioUrl(v);if(src && a.getAttribute("src")!==src){a.src=src;a.load()}else if(!src){a.removeAttribute("src");a.load()}
 if(record){history=[keyOf(v),...history.filter(x=>String(x)!==keyOf(v))].slice(0,20);persist()}
 renderCarousel();
}
function renderMaterialsMini(){
 const v=videos[active], ms=materials.filter(m=>m.video_title===v.title);const list=ms.length?ms:[{title:"Makna dan manfaat "+v.title},{title:"Cara melafalkan yang benar"},{title:"Waktu terbaik untuk melantunkan"},{title:"Hikmah dalam kehidupan sehari-hari"}];
 $("activeMaterialList").innerHTML=list.slice(0,4).map((m,i)=>`<div class="material-row"><i>${i+1}</i><span>${esc(m.title)}</span></div>`).join("");
}
function toggleFav(k){favorites.has(String(k))?favorites.delete(String(k)):favorites.add(String(k));persist();setActive(active,false);say("Favorit diperbarui")}
function toggleList(k){playlist.has(String(k))?playlist.delete(String(k)):playlist.add(String(k));persist();renderCarousel();say("Playlist diperbarui")}
$("infoFavBtn").onclick=()=>toggleFav(keyOf(videos[active]));
function renderTutorial(){const g=$("tutorialGrid");g.innerHTML=videos.map((v,i)=>`<div class="content-box" data-i="${i}"><img src="${esc(thumb(v))}" style="width:100%;height:125px;object-fit:cover;border-radius:8px;margin-bottom:8px"><h3>${esc(v.title)}</h3><p>${esc(v.pinyin||v.description||"")}</p><div class="card-actions"><button class="mini-btn">Buka</button></div></div>`).join("");g.querySelectorAll(".content-box").forEach(x=>x.onclick=()=>{setActive(+x.dataset.i,true);showPage("dashboard")})}
function renderListPage(id,keys){const g=$(id),inds=keys.map(k=>videos.findIndex(v=>keyOf(v)===String(k))).filter(i=>i>=0);g.innerHTML=inds.length?inds.map(i=>`<div class="content-box" data-i="${i}"><h3>${esc(videos[i].title)}</h3><p>${esc(videos[i].pinyin||videos[i].category||"")}</p></div>`).join(""):`<div class="content-box"><p>Belum ada data.</p></div>`;g.querySelectorAll("[data-i]").forEach(x=>x.onclick=()=>{setActive(+x.dataset.i,true);showPage("dashboard")})}
function renderCategories(){const c={};videos.forEach(v=>c[v.category||"Lainnya"]=(c[v.category||"Lainnya"]||0)+1);$("categoryGrid").innerHTML=Object.entries(c).map(([k,n])=>`<div class="content-box"><h3>${esc(k)}</h3><p>${n} bacaan</p></div>`).join("")}
function renderFAQ(){$("faqList").innerHTML=(faqs.length?faqs:[{question:"Bagaimana cara membaca mantra?",answer:"Pilih video/mantra lalu ikuti audio dan materi."}]).map((f,i)=>`<div class="doc-item"><h3>${esc(f.question)}</h3><p>${esc(f.answer)}</p>${f.important_note?`<p><b>Catatan:</b> ${esc(f.important_note)}</p>`:""}<div class="doc-actions"><button class="mini-btn" data-e="${i}">Edit</button><button class="mini-btn" data-d="${i}">Hapus</button></div></div>`).join("");$("faqList").querySelectorAll("[data-e]").forEach(b=>b.onclick=()=>openFaqForm(+b.dataset.e));$("faqList").querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>deleteFaq(+b.dataset.d))}
function renderSOP(){$("sopList").innerHTML=(sops.length?sops:[{title:"Panduan Pelafalan",content:"Baca dengan tenang, jelas, dan konsisten."}]).map((f,i)=>`<div class="doc-item"><h3>${esc(f.title)}</h3><p>${esc(f.content)}</p><div class="doc-actions"><button class="mini-btn" data-e="${i}">Edit</button><button class="mini-btn" data-d="${i}">Hapus</button></div></div>`).join("");$("sopList").querySelectorAll("[data-e]").forEach(b=>b.onclick=()=>openSopForm(+b.dataset.e));$("sopList").querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>deleteSop(+b.dataset.d))}
$("openMaterialDetail").onclick=()=>openMaterialDetail();$("materialBack").onclick=()=>showPage("dashboard");
function openMaterialDetail(index=0){const v=videos[active],ms=materials.filter(m=>m.video_title===v.title);const list=ms.length?ms:[{title:"Teks & Pinyin",category:v.category,summary:"Panduan baca",content:(v.hanzi||"")+"\n\n"+(v.reading||"")}];const m=list[Math.max(0,Math.min(index,list.length-1))];$("materialVideoTitle").textContent=v.title;$("materialCategory").textContent=m.category||"Materi";$("materialTitle").textContent=m.title;$("materialSummary").textContent=m.summary||"";$("materialBody").textContent=m.content||"";$("materialNav").innerHTML=list.map((x,i)=>`<button class="mini-btn" data-i="${i}">${esc(x.title)}</button>`).join("");$("materialNav").querySelectorAll("button").forEach(b=>b.onclick=()=>openMaterialDetail(+b.dataset.i));showPage("materi-detail")}
const a=$("nativeAudio");function play(){if(!a.getAttribute("src"))return say("Audio/video belum ditambahkan");a.paused?a.play():a.pause()}$("playBtn").onclick=play;$("heroBigPlay").onclick=play;a.onplay=()=>{$("playBtn").textContent="❚❚";$("heroBigPlay").textContent="❚❚"};a.onpause=()=>{$("playBtn").textContent="▶";$("heroBigPlay").textContent="▶"};a.ontimeupdate=()=>{const m=Math.floor(a.currentTime/60),s=Math.floor(a.currentTime%60),dm=Math.floor((a.duration||0)/60),ds=Math.floor((a.duration||0)%60);$("playerTime").textContent=`${m}:${String(s).padStart(2,"0")} / ${dm}:${String(ds).padStart(2,"0")}`;$("playerProgress").style.width=((a.currentTime/(a.duration||1))*100)+"%"};$("playerTrack").onclick=e=>{if(!a.duration)return;let r=e.currentTarget.getBoundingClientRect();a.currentTime=(e.clientX-r.left)/r.width*a.duration};$("volumeBtn").onclick=()=>{a.muted=!a.muted;$("volumeBtn").textContent=a.muted?"🔇":"🔊"};$("fullscreenBtn").onclick=()=>$("mainPlayer").requestFullscreen?.();
$("globalSearch").oninput=e=>{let q=e.target.value.trim().toLowerCase(),items=[];if(q){videos.forEach((v,i)=>{if([v.title,v.pinyin,v.category,v.description].join(" ").toLowerCase().includes(q))items.push({t:v.title,s:"Video",f:()=>{setActive(i,true);showPage("dashboard")}})});faqs.forEach(f=>{if([f.question,f.answer].join(" ").toLowerCase().includes(q))items.push({t:f.question,s:"FAQ",f:()=>showPage("faq")})});sops.forEach(f=>{if([f.title,f.content].join(" ").toLowerCase().includes(q))items.push({t:f.title,s:"SOP",f:()=>showPage("sop")})});materials.forEach(m=>{if([m.title,m.content].join(" ").toLowerCase().includes(q))items.push({t:m.title,s:"Materi",f:()=>{let i=videos.findIndex(v=>v.title===m.video_title);if(i>=0){setActive(i,false);openMaterialDetail()}}})})}$("searchResults").innerHTML=items.length?items.slice(0,12).map((x,i)=>`<div class="search-item" data-i="${i}"><b>${esc(x.t)}</b><small>${x.s}</small></div>`).join(""):(q?'<div class="search-item"><small>Tidak ditemukan.</small></div>':"");$("searchResults").classList.toggle("show",!!q);$("searchResults").querySelectorAll("[data-i]").forEach(n=>n.onclick=()=>{items[+n.dataset.i].f();$("searchResults").classList.remove("show")})}
$$("[data-close]").forEach(b=>b.onclick=()=>b.closest(".modal").classList.remove("show"));$$(".modal").forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove("show")});
function applyRole(){document.body.classList.toggle("is-admin",isAdmin);document.body.classList.toggle("is-owner",isOwner);$$(".admin-only").forEach(x=>x.style.display=isAdmin?"":"none");$("adminAuthBtn").textContent=session?"Keluar":"🔐 Admin Login";$("adminUserLabel").textContent=session?(session.user.email||""):""}
async function initSB(){const c=window.BUDDHIST_CONFIG||{};if(!window.supabase||!c.supabaseUrl)return;sb=window.supabase.createClient(c.supabaseUrl,c.supabaseAnonKey);await syncRemote();const {data:{session:s}}=await sb.auth.getSession();if(s)await setSession(s);sb.auth.onAuthStateChange(async(_e,sess)=>{sess?await setSession(sess):clearSession()})}
async function setSession(s){session=s;const {data:r}=await sb.from("user_roles").select("role,is_owner,approved").eq("user_id",s.user.id).maybeSingle();role=r?.role||"viewer";isOwner=!!r?.is_owner;isAdmin=!!(r?.approved&&(r.role==="admin"||r.is_owner));applyRole()}
function clearSession(){session=null;role="viewer";isAdmin=false;isOwner=false;applyRole()}
async function syncRemote(){if(!sb)return;try{let [v,m,f,s]=await Promise.all([sb.from("buddhist_videos").select("*").eq("is_deleted",false).order("id"),sb.from("buddhist_materials").select("*").order("id"),sb.from("buddhist_faq").select("*").order("id"),sb.from("buddhist_sop").select("*").order("id")]);if(v.data?.length)videos=v.data.map((r,i)=>{let b=base.find(x=>x.title===r.title)||base[i]||{};return {...b,...r,pinyin:(r.tags||[]).find(x=>x!=="mantra")||b.pinyin||"",audio:b.audio||r.video_url||"",thumb:r.thumbnail_url||b.thumb||"assets/thumb-1.png",hanzi:b.hanzi||"",reading:b.reading||""}});materials=m.data||[];faqs=f.data||[];sops=s.data||[];renderCarousel();renderMaterialsMini()}catch(e){console.warn(e)}}
$("adminAuthBtn").onclick=()=>{if(session&&sb){sb.auth.signOut();return}$("authModal").classList.add("show")};$("loginTab").onclick=()=>{authMode="login";$("loginTab").classList.add("active");$("registerTab").classList.remove("active");$("authSubmit").textContent="Login"};$("registerTab").onclick=()=>{authMode="register";$("registerTab").classList.add("active");$("loginTab").classList.remove("active");$("authSubmit").textContent="Daftar"};$("authSubmit").onclick=async()=>{if(!sb)return;$("authStatus").textContent="Memproses...";let email=$("authEmail").value.trim(),password=$("authPassword").value,res=authMode==="login"?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password});$("authStatus").textContent=res.error?res.error.message:"Berhasil";if(!res.error)setTimeout(()=>$("authModal").classList.remove("show"),500)}
$("openAddVideo").onclick=()=>openVideoForm();function openVideoForm(i=null){if(!isAdmin)return say("Khusus admin");editingVideo=i;let v=i==null?{}:videos[i];$("videoFormTitle").textContent=i==null?"Tambah Video":"Edit Video";$("videoTitle").value=v.title||"";$("videoPinyin").value=v.pinyin||"";$("videoCategory").value=v.category||"";$("videoDuration").value=v.duration||"";$("videoDescription").value=v.description||"";$("videoUrl").value=v.video_url||"";$("videoThumbnail").value=v.thumbnail_url||"";$("videoModal").classList.add("show")}
async function uploadFile(file,prefix){if(!file||!sb)return"";let name=`${prefix}/${Date.now()}-${file.name.replace(/[^\w.\-]+/g,"-")}`;let {error}=await sb.storage.from("buddhist-media").upload(name,file,{upsert:false});if(error)throw error;return sb.storage.from("buddhist-media").getPublicUrl(name).data.publicUrl}
$("saveVideo").onclick=async()=>{if(!sb||!isAdmin)return;try{$("videoStatus").textContent="Menyimpan...";let img=$("videoThumbnail").value.trim(),file=$("videoThumbFile").files[0];if(file)img=await uploadFile(file,"thumbnails");let row={title:$("videoTitle").value.trim(),category:$("videoCategory").value.trim(),description:$("videoDescription").value.trim(),duration:$("videoDuration").value.trim(),duration_label:$("videoDuration").value.trim(),language:"Indonesia",video_url:$("videoUrl").value.trim()||null,thumbnail_url:img||null,tags:["mantra",$("videoPinyin").value.trim()],is_deleted:false};let er;if(editingVideo==null){row.base_key="user-"+Date.now();er=(await sb.from("buddhist_videos").insert(row)).error}else er=(await sb.from("buddhist_videos").update(row).eq("id",videos[editingVideo].id)).error;if(er)throw er;await sb.rpc("log_activity",{p_action:editingVideo==null?"create":"update",p_target_type:"buddhist_video",p_target_name:row.title,p_detail:""});$("videoModal").classList.remove("show");await syncRemote();say("Video tersimpan")}catch(e){$("videoStatus").textContent=e.message}}
async function deleteVideo(i){if(!isAdmin||!confirm("Hapus video ini?"))return;let v=videos[i];if(v._local)return say("Video bawaan tidak dihapus dari fallback");let {error}=await sb.from("buddhist_videos").update({is_deleted:true}).eq("id",v.id);if(error)return say(error.message);await sb.rpc("log_activity",{p_action:"delete",p_target_type:"buddhist_video",p_target_name:v.title,p_detail:""});await syncRemote()}
$("addMaterialBtn").onclick=()=>openMaterialForm();function openMaterialForm(i=null){if(!isAdmin)return;editingMaterial=i;$("materialParent").innerHTML=videos.map(v=>`<option>${esc(v.title)}</option>`).join("");let m=i==null?{}:materials[i];$("materialFormTitleInput").value=m.title||"";$("materialFormCategory").value=m.category||"";$("materialFormSummary").value=m.summary||"";$("materialFormContent").value=m.content||"";$("materialParent").value=m.video_title||videos[active]?.title||"";$("materialModal").classList.add("show")}
$("saveMaterial").onclick=async()=>{if(!sb||!isAdmin)return;try{let attachment="",f=$("materialAttachment").files[0];if(f)attachment=await uploadFile(f,"attachments");let row={video_title:$("materialParent").value,title:$("materialFormTitleInput").value.trim(),category:$("materialFormCategory").value.trim(),summary:$("materialFormSummary").value.trim(),content:$("materialFormContent").value.trim(),attachment_url:attachment||null},er;if(editingMaterial==null)er=(await sb.from("buddhist_materials").insert(row)).error;else er=(await sb.from("buddhist_materials").update(row).eq("id",materials[editingMaterial].id)).error;if(er)throw er;$("materialModal").classList.remove("show");await syncRemote();say("Materi tersimpan")}catch(e){$("materialStatus").textContent=e.message}}
$("openFaqForm").onclick=()=>openFaqForm();function openFaqForm(i=null){editingFaq=i;let f=i==null?{}:faqs[i];$("faqQuestion").value=f.question||"";$("faqAnswer").value=f.answer||"";$("faqImportant").value=f.important_note||"";$("faqModal").classList.add("show")} $("saveFaq").onclick=async()=>{let row={question:$("faqQuestion").value.trim(),answer:$("faqAnswer").value.trim(),important_note:$("faqImportant").value.trim()||null},er=editingFaq==null?(await sb.from("buddhist_faq").insert(row)).error:(await sb.from("buddhist_faq").update(row).eq("id",faqs[editingFaq].id)).error;if(er)return say(er.message);$("faqModal").classList.remove("show");await syncRemote();renderFAQ()} async function deleteFaq(i){if(!confirm("Hapus FAQ?"))return;let er=(await sb.from("buddhist_faq").delete().eq("id",faqs[i].id)).error;if(er)return say(er.message);await syncRemote();renderFAQ()}
$("openSopForm").onclick=()=>openSopForm();function openSopForm(i=null){editingSop=i;let f=i==null?{}:sops[i];$("sopTitle").value=f.title||"";$("sopContent").value=f.content||"";$("sopModal").classList.add("show")} $("saveSop").onclick=async()=>{let row={title:$("sopTitle").value.trim(),content:$("sopContent").value.trim()},er=editingSop==null?(await sb.from("buddhist_sop").insert(row)).error:(await sb.from("buddhist_sop").update(row).eq("id",sops[editingSop].id)).error;if(er)return say(er.message);$("sopModal").classList.remove("show");await syncRemote();renderSOP()} async function deleteSop(i){if(!confirm("Hapus SOP?"))return;let er=(await sb.from("buddhist_sop").delete().eq("id",sops[i].id)).error;if(er)return say(er.message);await syncRemote();renderSOP()}
async function renderUsers(){if(!sb||!isOwner)return;$("userList").innerHTML="Memuat...";let {data,error}=await sb.from("user_roles").select("*").order("created_at");if(error)return $("userList").textContent=error.message;$("userList").innerHTML=(data||[]).map(u=>`<div class="doc-item"><h3>${esc(u.email||u.user_id)}</h3><p>${u.is_owner?"Owner":u.role} • ${u.approved?"Aktif":"Belum disetujui"}</p>${u.is_owner?"":`<div class="doc-actions" style="display:flex"><button class="mini-btn approve" data-id="${u.user_id}" data-role="viewer">Viewer</button><button class="mini-btn approve" data-id="${u.user_id}" data-role="admin">Admin</button><button class="mini-btn remove" data-id="${u.user_id}">Hapus</button></div>`}</div>`).join("");$("userList").querySelectorAll(".approve").forEach(b=>b.onclick=async()=>{let {error}=await sb.rpc("owner_set_user_access",{target_user_id:b.dataset.id,target_role:b.dataset.role});if(error)say(error.message);else renderUsers()});$("userList").querySelectorAll(".remove").forEach(b=>b.onclick=async()=>{if(!confirm("Hapus akun?"))return;let {error}=await sb.rpc("owner_delete_user",{target_user_id:b.dataset.id});if(error)say(error.message);else renderUsers()})}
async function renderLogs(){if(!sb||!isOwner)return;$("activityLogList").innerHTML="Memuat...";let {data,error}=await sb.from("activity_logs").select("*").order("created_at",{ascending:false}).limit(100);if(error)return $("activityLogList").textContent=error.message;$("activityLogList").innerHTML=(data||[]).map(x=>`<div class="doc-item"><h3>${esc(x.action)} • ${esc(x.target_type||"")}</h3><p>${esc(x.actor_email||"")} — ${esc(x.target_name||"")}<br><small>${new Date(x.created_at).toLocaleString()}</small></p></div>`).join("")}
renderCarousel();setActive(0,false);applyRole();initSB();
})();